version: '3'
services:
    pase-predictmod:
        build: ./
        volumes:
            - ./src:/app/
            - ./datasets:/datasets/
            - ./trained_models:/trained_models/
        ports:
            - "8888:80"
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: pase
        volumes:
            - ./init_mongodb:/docker-entrypoint-initdb.d